## Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

## Create a Dataframe

In [2]:

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Aarav", "Diya", "Kabir", "Meera", "Rohan", "Isha"],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE", "CSE"],
    "Marks_Math": [78, 65, 88, 72, None, 90],
    "Marks_AI": [85, 70, 92, None, 68, 95],
    "Marks_DS": [80, None, 89, 75, 70, 94],
    "Attendance": [92, 85, 96, 88, 80, 98],
    "Exam_Date": ["2024-03-10", "2024-03-10", "2024-03-11", "2024-03-11", "2024-03-12", "2024-03-12"]
}

df = pd.DataFrame(data)

In [3]:
print(df)

   Student_ID   Name Department  Marks_Math  Marks_AI  Marks_DS  Attendance  \
0         101  Aarav        CSE        78.0      85.0      80.0          92
1         102   Diya        ECE        65.0      70.0       NaN          85
2         103  Kabir        CSE        88.0      92.0      89.0          96
3         104  Meera         ME        72.0       NaN      75.0          88
4         105  Rohan        ECE         NaN      68.0      70.0          80
5         106   Isha        CSE        90.0      95.0      94.0          98

    Exam_Date
0  2024-03-10
1  2024-03-10
2  2024-03-11
3  2024-03-11
4  2024-03-12
5  2024-03-12

## Data Inspection

In [20]:
df.head()

,Student_ID,Name,Department,Marks_Math,Marks_AI,Marks_DS,Attendance,Exam_Date,Total_Marks,Average_Marks,Result,Grade
0,101,Aarav,CSE,78.0,85.0,80.0,92,2024-03-10,243.0,81.000000,Pass,B
1,102,Diya,ECE,65.0,70.0,81.6,85,2024-03-10,216.6,72.200000,Pass,B
2,103,Kabir,CSE,88.0,92.0,89.0,96,2024-03-11,269.0,89.666667,Pass,A
3,104,Meera,ME,72.0,82.0,75.0,88,2024-03-11,229.0,76.333333,Pass,B
5,106,Isha,CSE,90.0,95.0,94.0,98,2024-03-12,279.0,93.000000,Pass,A

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  6 non-null      int64
 1   Name        6 non-null      str
 2   Department  6 non-null      str
 3   Marks_Math  5 non-null      float64
 4   Marks_AI    5 non-null      float64
 5   Marks_DS    5 non-null      float64
 6   Attendance  6 non-null      int64
 7   Exam_Date   6 non-null      str
dtypes: float64(3), int64(2), str(3)
memory usage: 516.0 bytes

In [5]:
df.describe()

       Student_ID  Marks_Math   Marks_AI   Marks_DS  Attendance
count    6.000000    5.000000   5.000000   5.000000    6.000000
mean   103.500000   78.600000  82.000000  81.600000   89.833333
std      1.870829   10.573552  12.429803   9.864076    6.823977
min    101.000000   65.000000  68.000000  70.000000   80.000000
25%    102.250000   72.000000  70.000000  75.000000   85.750000
50%    103.500000   78.000000  85.000000  80.000000   90.000000
75%    104.750000   88.000000  92.000000  89.000000   95.000000
max    106.000000   90.000000  95.000000  94.000000   98.000000

## Data Cleaning

In [6]:
df.isna().sum()

Student_ID    0
Name          0
Department    0
Marks_Math    1
Marks_AI      1
Marks_DS      1
Attendance    0
Exam_Date     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['Exam_Date']=pd.to_datetime(df['Exam_Date'])

In [9]:
print(df['Exam_Date'].dtype)

datetime64[us]

In [10]:
df['Marks_Math']=df['Marks_Math'].fillna(df['Marks_Math'].mean())
df['Marks_AI']=df['Marks_AI'].fillna(df['Marks_AI'].mean())
df['Marks_DS']=df['Marks_DS'].fillna(df['Marks_DS'].mean())

In [11]:
df.isnull().sum()

Student_ID    0
Name          0
Department    0
Marks_Math    0
Marks_AI      0
Marks_DS      0
Attendance    0
Exam_Date     0
dtype: int64

In [12]:
df.drop(df[df['Attendance']<85].index,inplace=True)
#df=df[df['Attendance']>=85]

In [13]:
print(df)

   Student_ID   Name Department  Marks_Math  Marks_AI  Marks_DS  Attendance  \
0         101  Aarav        CSE        78.0      85.0      80.0          92
1         102   Diya        ECE        65.0      70.0      81.6          85
2         103  Kabir        CSE        88.0      92.0      89.0          96
3         104  Meera         ME        72.0      82.0      75.0          88
5         106   Isha        CSE        90.0      95.0      94.0          98

   Exam_Date
0 2024-03-10
1 2024-03-10
2 2024-03-11
3 2024-03-11
5 2024-03-12

## Feature Engineering

In [14]:
df['Total_Marks']=df['Marks_Math']+df['Marks_AI']+df['Marks_DS']
df['Average_Marks']=df['Total_Marks']/3

In [15]:
print(df)

   Student_ID   Name Department  Marks_Math  Marks_AI  Marks_DS  Attendance  \
0         101  Aarav        CSE        78.0      85.0      80.0          92
1         102   Diya        ECE        65.0      70.0      81.6          85
2         103  Kabir        CSE        88.0      92.0      89.0          96
3         104  Meera         ME        72.0      82.0      75.0          88
5         106   Isha        CSE        90.0      95.0      94.0          98

   Exam_Date  Total_Marks  Average_Marks
0 2024-03-10        243.0      81.000000
1 2024-03-10        216.6      72.200000
2 2024-03-11        269.0      89.666667
3 2024-03-11        229.0      76.333333
5 2024-03-12        279.0      93.000000

In [16]:
df['Result']=np.where(df['Average_Marks']>=60,'Pass','Fail')
#np.where(condition, value_if_true, value_if_false)
#df['Result'] = df['Average_Marks'].apply( lambda x: 'Pass' if x >= 60 else 'Fail')

In [17]:
print(df['Result'])

0    Pass
1    Pass
2    Pass
3    Pass
5    Pass
Name: Result, dtype: str

In [18]:
def grades(x):
    if x>=85:
      return 'A'
    elif x>=70:
      return 'B'
    elif x>=60:
      return 'C'
    else:
      return 'D'

df['Grade']=df['Average_Marks'].apply(grades)

In [19]:
df.head()

,Student_ID,Name,Department,Marks_Math,Marks_AI,Marks_DS,Attendance,Exam_Date,Total_Marks,Average_Marks,Result,Grade
0,101,Aarav,CSE,78.0,85.0,80.0,92,2024-03-10,243.0,81.000000,Pass,B
1,102,Diya,ECE,65.0,70.0,81.6,85,2024-03-10,216.6,72.200000,Pass,B
2,103,Kabir,CSE,88.0,92.0,89.0,96,2024-03-11,269.0,89.666667,Pass,A
3,104,Meera,ME,72.0,82.0,75.0,88,2024-03-11,229.0,76.333333,Pass,B
5,106,Isha,CSE,90.0,95.0,94.0,98,2024-03-12,279.0,93.000000,Pass,A

## Advanced Analysis

In [21]:
#department-wise average marks
group=df.groupby('Department')['Average_Marks'].mean()
print(group)

Department
CSE    87.888889
ECE    72.200000
ME     76.333333
Name: Average_Marks, dtype: float64

In [22]:
#topper of each department
topper=df.loc[df.groupby('Department')['Total_Marks'].idxmax(),['Department','Name']]
print(topper)

  Department   Name
5        CSE   Isha
1        ECE   Diya
3         ME  Meera

In [23]:
#attendance-weighted score
df['Weighted_Score']=df['Average_Marks']*(df['Attendance']/100)
print(df['Weighted_Score'])

0    74.520000
1    61.370000
2    86.080000
3    67.173333
5    91.140000
Name: Weighted_Score, dtype: float64

## Reshaping & Filtering

In [29]:
pivot=pd.pivot_table(df,index='Department',columns='Grade',values='Student_ID',aggfunc='count',fill_value=0)
print(pivot)

Grade       A  B
Department
CSE         2  1
ECE         0  1
ME          0  1

In [30]:
students=df[(df['Grade']=='A')& (df['Attendance']>=90)]['Name']
print(students)

2    Kabir
5     Isha
Name: Name, dtype: str